<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-48HCJLNU" failures="10" tests="173" name="testrunners.MyTestRunner" time="112.556" errors="0" timestamp="2023-08-04T17:25:06 EDT" skipped="0">
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.405"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.485"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.885"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.258"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.387"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.615"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.300"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.616"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.863"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.878"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.690"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.464"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.655"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.166"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.403"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.576"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.690"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.386"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.517"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.412"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.823"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.772">
    <failure message="expected [Successful Submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_four(ArraySteps.java:647)
at ✽.The user should be presented with successful submission message on question four(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/FArray.feature:236)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.566"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.228"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.654"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.840"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.295"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.306"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.411"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.496"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.189"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.795"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.537"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.528"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.844"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.406"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.390"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.501"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.173"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.866"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.286"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.367"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.035"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.338"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.405"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.075"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.545"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.612"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.743"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.567"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.968"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.604">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password should contain at least 8 characters"(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:48)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.599">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password can’t be entirely numeric."(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.136"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.465"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.547"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.388"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.177"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.715"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.260"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.360"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.529"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.697"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.176"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.515"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.291"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.321"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.754"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.177"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.520"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.053"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.542"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.715"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.597"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.395"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.454"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.631">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Please enter a valid username"(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.565">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Username already exists"(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.622"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.566">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password can’t be commonly used password"(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.327"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.356"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.399"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.679"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.531"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.803"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.683"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.835"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.909"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.742"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.284"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.344"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.096"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.276"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.921"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.022">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_two(ArraySteps.java:489)
at ✽.The user should be presented with successful submission message on question two(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/FArray.feature:176)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.933"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.502"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.533"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.681"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.362"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.720"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.494"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.829"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.379"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.499"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.362"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.354"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.998"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.347"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.293"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.303"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.445"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.729"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.428"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.178"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.820"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.602"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.364"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.735"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.275"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.551">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "password can’t be too similar to your other personal information."(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/CRegister.feature:62)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.315"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.646">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_three(ArraySteps.java:569)
at ✽.The user should be presented with successful submission message on question three(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/FArray.feature:207)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.340"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.172"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.516"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.534"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.900"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.778"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.380"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.739"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.694">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_for_search_the_array(ArraySteps.java:410)
at ✽.The user should be presented with successful submission message for Search the array(file:///C:/Users/subul/git/BDDproject/src/test/resources/features/FArray.feature:145)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.816"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.259"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.173"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.916"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.276"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.408"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.368"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.167"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.429"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.650"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.295"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.779"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.878"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.365"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.215"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.172"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.429"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.976"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.334"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.257"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.353"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.330"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.691"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.464"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.876"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.222"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.342"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.491"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.352"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.872"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.579"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.392"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.883"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.360"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.219"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.508"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.171"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.154"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.194"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.421"/>
</testsuite> <!-- testrunners.MyTestRunner -->
